version: '3'

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - ${ZIPKIN_PORT:-9411}:9411
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - ${RABBIT_PORT:-5672}:5672

