version: '3'

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: docker-images.dimed.com.br:5000/zipkin
    container_name: zipkin
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - ${ZIPKIN_PORT:-9411}:9411
    depends_on:
      - rabbitmq

  rabbitmq:
    image: docker-images.dimed.com.br:5000/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - ${RABBIT_PORT:-5672}:5672
      - ${RABBIT_PORT:-15672}:15672